vich_uploader:
    db_driver: orm

    mappings:
        betises:
            uri_prefix: /images/betises
            upload_destination: '%kernel.project_dir%/public/images/betises'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true